### ISSUE TITLE
FR: Proper sudo for the official Docker images

### ISSUE THREAD

**Issue by gerroon** [Oxygem/Kanmail#105]
Hi

It would be nice if the container includes proper sudo. It might sounds unreasonable but I wanted to inspect `/root/.config/kanmail`

```
docker exec -ti kanmail sh
/opt/kanmail $ cd /root/
sh: cd: can't cd to /root/: Permission denied
/opt/kanmail $ su
su: must be suid to work properly
/opt/kanmail $ sudo
sh: sudo: not found
/opt/kanmail $ sudo su
sh: sudo: not found

```

https://unix.stackexchange.com/questions/573215/how-to-install-sudo-when-i-dont-have-sudo-or-su 

The reason is that I provided a permanent volume however it is empty after setting up some account and settings. This should not be the case. Providing volumes always work for me, I have 10s of Dockers running here that way. Upgrading this container means I will loose all the changes. I just wanted to check if `/root/.config/kanmail` was truelly empty or where the settings were saved.

thanks

**Comment by Fizzadar** [comment]
This directory has actually changed in the latest version due to the addition of the `kanmail` user, I have updated the Docker docs to reflect this now (https://github.com/Oxygem/Kanmail/commit/01d6e7c21ff1facbac7b72b2143391d0583997de).

If you're using an old version you can still get root access without sudo by using `docker exec --user root -ti kanmail sh`.
